version: 2
jobs:
  build:
    docker:
      - image: openjdk-11-boot-2.8.3-buster-node-browsers-legacy
    working_directory: ~/idle-parens
    steps:
      - checkout
      - run: boot build
      - persist_to_workspace:
          root: target
          paths: public

  deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: target
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email ${GIT_USER_EMAIL}
            git config user.name ${GIT_USER_NAME}
      - add_ssh_keys:
          fingerprints:
            - "fc:61:02:7a:a5:ef:6b:0c:71:90:15:e8:62:63:94:03"
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            gh-pages --dist target/public \
                     --repo git@github.com:${GIT_DEST} \
                     --branch master

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
